server {
    listen 80;
    include /etc/nginx/mime.types;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Evita que Nginx devuelva el index.html para archivos estáticos (.js, .css) que ya no existen
    # Esto ocurre comúnmente en PWAs al lanzar una nueva versión (caché pidiendo chunks antiguos)
    location ~* \.(?:css|js)$ {
        root /usr/share/nginx/html;
        try_files $uri =404;
    }
}